language: ruby
rvm:
  - 1.9.3
  - 1.9.2
env:
  - TEST_CONFIG=test_mysql
  - TEST_CONFIG=test_sqlite
  - TEST_CONFIG=test_postgres
before_script:
  - sh -c "if [ '$TEST_CONFIG' = 'test_mysql' ]; then mysql -e 'create database specifind_test;' --user=root;  fi"
  - sh -c "if [ '$TEST_CONFIG' = 'test_postgres' ]; then psql -c 'create database specifind_test;' -U postgres; fi"