test:
  adapter: mysql2
  database: specifind_test
  username: mlahey
  encoding: utf8

test_mysql:
  adapter: mysql2
  database: specifind_test
  username: root
  encoding: utf8
  
test_postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres