test:
  adapter: mysql2
  database: specifind_test
  username: mlahey
  encoding: utf8

test_sqlite:
  adapter: sqlite3
  database: spec/spec.sqlite3

test_mysql:
  adapter: mysql2
  database: specifind_test
  username: root
  encoding: utf8
  
test_postgres:
  adapter: postgresql
  database: specifind_test
  username: postgres